@startuml
'https://plantuml.com/class-diagram

class Folder {
    - folderName: String
    - subFolders: ArrayList<Folder>
    - files: ArrayList<File>

    + Folder()
    + getFolderName(): String
    + setFolderName(folderName: String): void
    + removeSubFolder(subFolderName: String): void
    + addSubFolder(subFolderName: String): void
    + getSubFolder(subFolderName: String): Folder
    + removeFile(file: File): boolean
    + addFile(fileName: String): void
    + print(): void
}

class File{
    - fileName: String

    + File(fileName: String)
    + getFileName(): String
    + setFileName(fileName: String): void
    + print(): void
}

class Driver {
    + main(args: String[]): void
}

Folder *-- File : contains
Folder *-- Folder : subfolder

Driver ..> Folder
@enduml