@startuml
'https://plantuml.com/object-diagram

object "ships[0]: Ship" as ships[0] {
    name = "Titanic"
    yearBuilt = 1917
}

object "ships[1]: CruiseShip" as ships[1] {
    name = "My boat"
    yearBuilt = 2005
    maxPassengers = 10
}

object "ships[2]: CargoShip" as ships[2]{
    name = "Crate boat"
    yearBuilt = 1977
    cargoCapacity = 59
}

@enduml
